name: todoapp
description: ToDo App

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase database
  cloud_firestore: ^2.4.0

  # Google Icon
  font_awesome_flutter: ^9.1.0

  # Authentication
  firebase_auth: ^1.4.1
  google_sign_in: ^5.0.4
  flutter_facebook_auth: ^3.5.0

  # State Management
  provider: ^5.0.0
  
  # Bottom Navigation Bar
  bottom_navy_bar: ^6.0.0
  
  # # Appbar Gradient
  # new_gradient_app_bar: ^0.2.0

  # Splash Screen
  flutter_native_splash: ^1.2.0
  
  # Login Animations
  flutter_login: ^2.2.0

  # Slidable Animations
  flutter_slidable: ^0.6.0

  # Add this after it is out of dev mode
  # # Launcher Icon
  # flutter_launcher_icons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# Add this after it is out of dev mode
# flutter_icons:
#   image_path: "assets/logo/feather.png"
#   android: true
#   ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets\logo\feather.png
  color_dark: "#1a1a1a"
  image_dark: assets\logo\feather.png
  ios: true
  android: true

flutter:
  uses-material-design: true

  fonts:
    - family: Caveat
      fonts: 
        - asset: assets/fonts/Caveat-Regular.ttf
        - asset: assets/fonts/Caveat-Medium.ttf
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
        - asset: assets/fonts/RobotoSlab-Medium.ttf
        - asset: assets/fonts/RobotoSlab-SemiBold.ttf
          weight: 500
    - family: Tourney
      fonts: 
        - asset: assets/fonts/Tourney-Medium.ttf
        - asset: assets/fonts/Tourney-Regular.ttf
        - asset: assets/fonts/Tourney-SemiBold.ttf
          weight: 500
    - family: Roboto
      fonts: 
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 500

  assets:
    - assets/logo/feather.png