name: todoapp
description: ToDo App

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Google Icon
  font_awesome_flutter: ^9.1.0

  # Google Sign In
  firebase_auth: ^1.4.1
  google_sign_in: ^5.0.4

  # State Management
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true